
import java.awt.CardLayout;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import org.semanticweb.owlapi.model.OWLException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cirom
 */
public class OutputTableaux extends javax.swing.JFrame {
       
    private Tableaux tableauxReference;
    private DataByFrame dataInterface;
    private float timeElapsed;
    
    
    public  void showImage(BufferedImage img){
        JFrame frame = new JFrame("Tableaux");
        frame.setLayout(new FlowLayout());
        
        frame.setLocation(100,100);
        ImageIcon imgIcon = new ImageIcon(img);
        frame.add(new JLabel(imgIcon));
        frame.setSize(imgIcon.getIconWidth()+100, imgIcon.getIconHeight()+150);
        JButton saveRdfTableaux = new JButton();
         saveRdfTableaux.setSize(50,30);
        saveRdfTableaux.setText("Salva Tableaux");
      /*  saveRdfTableaux.setAlignmentY(imgIcon.getIconHeight()+40);
        saveRdfTableaux.setAlignmentX(imgIcon.getIconWidth()+40);
        saveRdfTableaux.setHorizontalAlignment(SwingConstants.RIGHT);*/
        saveRdfTableaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
               this.saveRdfTableauxActionPerformed(evt);
            }

            private void saveRdfTableauxActionPerformed(ActionEvent evt) {
                try {
                    tableauxReference.save("Tableaux.rdf");
                } catch (OWLException ex) {
                    Logger.getLogger(OutputTableaux.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(OutputTableaux.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        
        frame.add(saveRdfTableaux);
        frame.setAlwaysOnTop(true);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
   
    
    
    private float getTime(){
        return timeElapsed;
    }
    
    private void setTime(float time){
        timeElapsed = time;
    }
    
    /**
     * Creates new form OutputTableaux
     */
    public OutputTableaux(DataByFrame data) {
     
    }
    public OutputTableaux(DataByFrame data,float time) {
        setTime(time);
        try {
            initComponents();
            dataInterface = data;
            tableauxReference = dataInterface.getTableauxReference();
            conceptText.setText(tableauxReference.getConcept());
           // conceptText.setSize(100, 100);
            conceptText.setVisible(true);
             if(tableauxReference.isClashFree()){
                 risClashes.setText("E' SODDISFACIBILE");
              //   risClashes.setSize(100, 100);
                 risClashes.setVisible(true);
             }else {
                risClashes.setText("E' INSODDISFACIBILE");
               // risClashes.setSize(100, 100);
                risClashes.setVisible(true);
                listClashes.setText("Ecco i Clash: "+tableauxReference.getClashes());
                listClashes.setVisible(true);
            }
            computationalTime.setText(getTime()+"ms");
            computationalTime.setVisible(true);
            
        } catch (OWLException ex) {
            Logger.getLogger(OutputTableaux.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        fieldConceptInserted = new javax.swing.JLabel();
        showedConceptLabel = new javax.swing.JLabel();
        risTableaux = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timeMethod = new javax.swing.JLabel();
        showGraphButton = new javax.swing.JButton();
        newConceptButton = new javax.swing.JButton();
        closeFrameButton = new javax.swing.JButton();
        conceptText = new javax.swing.JLabel();
        risClashes = new javax.swing.JLabel();
        listClashes = new javax.swing.JLabel();
        computationalTime = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Risultato");

        fieldConceptInserted.setText("Il Concetto inserito:");

        jLabel2.setText("Tempo di Computazione:");

        showGraphButton.setBackground(new java.awt.Color(0, 153, 255));
        showGraphButton.setText("Mostra Grafo");
        showGraphButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphButtonActionPerformed(evt);
            }
        });

        newConceptButton.setText("Nuovo Concetto");
        newConceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newConceptButtonActionPerformed(evt);
            }
        });

        closeFrameButton.setText("Chiudi");
        closeFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFrameButtonActionPerformed(evt);
            }
        });

        conceptText.setText(" ");

        risClashes.setText(" ");

        listClashes.setText(" ");

        computationalTime.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(216, 216, 216)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fieldConceptInserted)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(risTableaux, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(risClashes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(conceptText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(showedConceptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(listClashes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(computationalTime, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(closeFrameButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(newConceptButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(showGraphButton))
                                    .addComponent(timeMethod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldConceptInserted, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showedConceptLabel)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(conceptText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(risTableaux)
                .addGap(18, 18, 18)
                .addComponent(risClashes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listClashes)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(timeMethod)
                    .addComponent(computationalTime))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showGraphButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(newConceptButton)
                        .addComponent(closeFrameButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphButtonActionPerformed
        BufferedImage img;
        try {
            img = tableauxReference.toImage(false);
                showImage(img);
        } catch (IOException ex) {
            Logger.getLogger(OutputTableaux.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_showGraphButtonActionPerformed

    private void newConceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newConceptButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        MainFrame newFrame = new MainFrame();
        newFrame.setAlwaysOnTop(true);
        newFrame.setVisible(true);
    }//GEN-LAST:event_newConceptButtonActionPerformed

    private void closeFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFrameButtonActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_closeFrameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OutputTableaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OutputTableaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OutputTableaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OutputTableaux.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new OutputTableaux().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeFrameButton;
    private javax.swing.JLabel computationalTime;
    private javax.swing.JLabel conceptText;
    private javax.swing.JLabel fieldConceptInserted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel listClashes;
    private javax.swing.JButton newConceptButton;
    private javax.swing.JLabel risClashes;
    private javax.swing.JLabel risTableaux;
    private javax.swing.JButton showGraphButton;
    private javax.swing.JLabel showedConceptLabel;
    private javax.swing.JLabel timeMethod;
    // End of variables declaration//GEN-END:variables
}
